### ISSUE TITLE
Installation on Mac

### ISSUE THREAD

**Issue by tangweiyi123** [VioletteChiara/AnimalTA#15]
Hi Violette,

You mentioned in the README that AnimalTA can be installed on Mac OS without installers. Can you describe how to do it? I did not find it in the guidelines either.

Weiyi

**Comment by VioletteChiara** [comment]
Hello,

Unfortunately installing AnimalTA on MacOS without installer is very complicated, but you can have a look at those discussion: https://github.com/VioletteChiara/AnimalTA/discussions/11#discussion-5718236

Another option is to use virtualization software. We have good feedback from users using UTM (https://mac.getutm.app/) or Parallel Desktop (https://www.parallels.com/products).
