### ISSUE TITLE
Error when updating to new version

### ISSUE THREAD

**Issue by dnews13** [VioletteChiara/AnimalTA#18]
Hi, I just saw that the program was updated. It looks like some great changes!

However, once installed, I tried to open it and ran into an error. Of note, I did overwrite the original installation with this new one. The computer runs Windows 10 Pro.

![IMG_4161](https://github.com/VioletteChiara/AnimalTA/assets/147422562/648d980e-a9d0-4939-b857-40c1822d1149)

Please advise. Thank you in advance!

**Comment by VioletteChiara** [comment]
Hello,
I am sorry you are facing difficulties with AnimalTA. This problem often occurs when you have an older version of AnimalTA installed and the update creates a problem with the new version. Please try to uninstall AnimalTA (all versions) from your computer and install it again. It usually solves the problem.

Thank you for being interested in AnimalTA!

**Comment by dnews13** [comment]
Perfect! New version up and running. Thank you so much for always being so quick and helpful with your responses. Very excited to use the program in my project.
