### ISSUE TITLE
Problems with the instalation

### ISSUE THREAD

**Issue by danikinoshita** [VioletteChiara/AnimalTA#19]
Hi, so I have the program installed in another computer, but I had to change it. When tried to install it in the new one, this problem showed up

![WhatsApp Image 2024-07-31 at 12 17 45](https://github.com/user-attachments/assets/aa6378da-c1cb-4036-a8a2-517c9a41923d)

**Comment by VioletteChiara** [comment]
Hello,

This usually occurs when there is a problem with an update. I invite you to uninstall both versions of the program before re-installing the new one.

I hope this is helpful.

Best regards
